---
- hosts: localhost
  connection: local
  tasks:
    - timetest:
      #  time: 2017-01-01 00:00:00
      #with_items:
      #  - a
      #  - b
      register: timetest_result
    - debug: var=timetest_result
...
